# Vim, with a set of extra packages (extraPackages) and a custom vimrc
# (./vimrc). The final vimrc file is generated by vimUtils.vimrcFile and
# bundles all the packages with the custom vimrc.
{ fetchGit, symlinkJoin, makeWrapper, node, python3, pythonPackages, python3Packages, vim_configurable, vimUtils, vimPlugins }:
let
  customPlugins = {
    vim-colemakz = vimUtils.buildVimPlugin {
      name = "vim-colemakz";
      src = fetchTarball {
        url = https://github.com/jooize/vim-colemak/archive/b596bd60662116226ed021fcfa0ecd7ceb45329e.tar.gz;
        sha256 = "1ix8pyn07hjjd1dz80x474sjxbc1f78jh4kzfjhv78jjj4r1p26j";
      };
    };
    lightline-vim = vimUtils.buildVimPlugin {
      name = "lightline-vim";
      src = fetchTarball {
        url = https://github.com/itchyny/lightline.vim/archive/688240e0ef849cdc8457822658cedf10358c75d6.tar.gz;
        sha256 = "1rv8cj553h7w9y61vswq7s9hfmr5h2vxghqrkcsr6vvn7fy6smiv";
      };
    };
    lightline-ale = vimUtils.buildVimPlugin {
      name = "lightline-ale";
      src = fetchTarball {
        url = https://github.com/maximbaz/lightline-ale/archive/dd59077f9537b344f7ae80f713c1e4856ec1520c.tar.gz;
        sha256 = "1f9v6nsksy36s5i27nfx6vmyfyjk27p2w2g6x25cw56b0r3sgxmx";
      };
    };
    /*
    neoterm = vimUtils.buildVimPlugin {
      name = "neoterm";
      src = fetchTarball {
        url = https://github.com/kassio/neoterm/archive/1cd039297d402b8610981bd51b7a2c0276b87467.tar.gz;
        sha256 = "01n9560c3agry5aynqj86ivd22n2b22jig4vr5xzwynqwfh1drb9";
      };
      };
      */
    choosewin = vimUtils.buildVimPlugin {
      name = "choosewin";
      src = fetchTarball {
        url = https://github.com/t9md/vim-choosewin/archive/4ac141a9bb7188ebbbff90bb0a0bccd52eaa83f8.tar.gz;
        sha256 = "08glj4fk4jlcdqbyd77dwy3rbn3vc0fqz077fwvkxym47hfg9rqk";
      };
    };
    goldenview = vimUtils.buildVimPlugin {
      name = "goldenview";
      src = fetchTarball {
        url = https://github.com/zhaocai/GoldenView.Vim/archive/ac0ee3014caa36c52e8352d11c308b27a159113c.tar.gz;
        sha256 = "1gzp81spsbg20svwd14rixhgl39ir458p5k9q5jjv9l5rbnbinad";
      };
    };
    numbertoggle = vimUtils.buildVimPlugin {
      name = "numbertoggle";
      src = fetchTarball {
        url = https://github.com/jeffkreeftmeijer/vim-numbertoggle/archive/cfaecb9e22b45373bb4940010ce63a89073f6d8b.tar.gz;
        sha256 = "1rrmvv7ali50rpbih1s0fj00a3hjspwinx2y6nhwac7bjsnqqdwi";
      };
    };
    vim-drawer = vimUtils.buildVimPlugin {
      name = "vim-drawer";
      src = fetchTarball {
        url = https://github.com/samuelsimoes/vim-drawer/archive/e023619a24115d6dd62a7769a0eb35d4d3774d55.tar.gz;
        sha256 = "0y2lbggh59d3sb8wq52zqxh765kphv98gbssrjp7bkbvljcqaac2";
      };
    };

    # Completionist capabilities
    completor = vimUtils.buildVimPlugin {
      name = "completor";
      src = fetchTarball {
        url = https://github.com/maralla/completor.vim/archive/f5bddd6f0c488b95e3ea4052140338a4e3a923c2.tar.gz;
        sha256 = "0wv98j1xx4xjgc93rhpvwg5dsqbv84c79s9ywkl60rmkpa92qxbh";
      };
      # Makefile is broken 
      preBuild = "rm Makefile";
      #postInstall = "make js";
    };
    completor-dictionary = vimUtils.buildVimPlugin {
      name = "completor-dictionary";
      src = fetchTarball {
        url = https://github.com/masawada/completor-dictionary/archive/d594293ca44f9f75f89a91fef4406e06a145a8ab.tar.gz;
        sha256 = "0wv98j1xx4xjgc93rhpvwg5dsqbv84c79s9ywkl60rmkpa92qxbh";
      };
      # Makefile is broken 
      preBuild = "rm Makefile";
      #postInstall = "make js";
    };

    /* TODO
    vim-sneak = vimUtils.buildVimPlugin {
      name = "vim-sneak";
      src = fetchTarball {
        url = https://github.com/justinmk/vim-sneak/archive/91192d8969af1d86c98beff4001612976ea25d7a.tar.gz;
        sha256 = "0nmbrp0ma9s3yfzb8z70l0pcxv8p115zv6fz4injxn1c436x9337";
      };
      };
      */

    # For nix known Python Dependencies the following can be used
    # Alternatively as Python tends to be out of date, pypi2nix loading tends to be more convenient and reliable. 
    #pythonDependencies = with python3Packages; [ pynvim ];
  };
  extraPackages = with vimPlugins;
    [
      vim-polyglot
      vim-dirvish
      vim-eunuch
      vim-unimpaired
      fzf-vim
      ale
      vim-commentary
      vim-repeat
      vim-gitgutter
      vim-test
      editorconfig-vim
      vim-obsession
      vim-indent-guides
      vim-jinja
      auto-pairs
      vim-auto-save
      vim-dispatch
      papercolor-theme
    ]
    ++ builtins.attrValues customPlugins;
  customRC = vimUtils.vimrcFile
    { customRC = builtins.readFile ./vimrc;
      packages.mvc.start = extraPackages;
    };

  # Extend Vim settings for additional compilation requirements  
  extend_vim = vim_configurable.override {
    python = python3;
  };  
in
symlinkJoin {
  name = "vim";
  buildInputs = [makeWrapper];
  postBuild = ''
    wrapProgram "$out/bin/vim" \
    --add-flags "-u ${customRC}" 
  '';
  paths = [ extend_vim ];
}
